#pragma once

#include "CryptoEngine.h"
#include "KeyringAdapter.h"

#include <QJsonObject>
#include <QString>
#include <QStringList>
#include <QVector>

/** A private key stored (optionally passphrase-protected) in the keyring vault. */
struct StoredKey {
    QString id;          // stable identifier referenced by SessionProfile::privateKeyId
    QString name;        // display name the user chose when importing
    QString type;        // key type label (e.g. "ed25519", "rsa") for the keychain view
    QString fingerprint; // OpenSSH-compatible SHA-256 public-key fingerprint
    QByteArray pem;      // the PEM payload (Base64) — encrypted at rest in the dbvault
    bool hasPassphrase = false; // passphrase required to decrypt/import this key
};

Q_DECLARE_METATYPE(StoredKey)

/**
 * Coordinates the on-disk vault:
 *
 *   File 1  connects.json — connection metadata (hosts/ports/user/names).
 *       Encrypted with a fast, machine-bound key derived in-memory
 *       (SHA-256 of machine-id + per-user scope). Decrypts near-instantly at
 *       launch with no OS keyring / DPAPI / keyring latency.
 *
 *   File 2  dbvault — sensitive material (passwords, passphrases).
 *       The whole file is AES-256-GCM encrypted; its 256-bit master key lives
 *       in the OS keyring (Credential Manager / Keychain / Secret Service),
 *       retrieved transparently at launch with graceful fallback.
 *
 * Both files are written atomically (temp file + rename) so a crash or power
 * loss cannot corrupt them. Decrypted payloads are returned to callers and the
 * dbvault master key is zeroed on destruction.
 */
class VaultManager
{
public:
    enum class LoadOutcome {
        Loaded,
        NotFound, // first run / nothing saved yet
        Corrupt   // present but could not be read/decrypted
    };

    VaultManager();
    ~VaultManager();

    // ---- Paths --------------------------------------------------------------
    static QString vaultDir();
    static QString connectsPath();
    static QString dbvaultPath();

    // ---- connects.json (fast metadata) --------------------------------------
    /** Decrypt connects.json into `plainOut`. */
    LoadOutcome loadConnectsJson(QByteArray& plainOut);
    /** Encrypt and atomically write `plain` to connects.json. */
    bool saveConnectsJson(const QByteArray& plain);
    bool connectsExists() const;

    // ---- dbvault (keyring-protected secrets) --------------------------------
    /**
     * Store a per-profile secret (base64) in the encrypted dbvault file.
     * Returns false on I/O or cipher failure.
     */
    bool storeSecret(const QString& profileId, const QString& field, const QByteArray& secret);
    /** Retrieve a per-profile secret. Returns false when absent/unreadable. */
    bool retrieveSecret(const QString& profileId, const QString& field, QByteArray& secretOut);
    /** Remove a per-profile secret; best-effort. */
    bool removeSecret(const QString& profileId, const QString& field);

    // ---- stored keys (reusable keyring entries, independent of profiles) -----
    /**
     * Persist (insert or update) a named private key in the keyring vault.
     * `key.id` must already be set; a new id is generated by the caller.
     */
    bool storeStoredKey(const StoredKey& key);
    /** Retrieve the stored key with `id`, or false when absent/unreadable. */
    bool retrieveStoredKey(const QString& id, StoredKey& keyOut);
    /** List every stored key (without the PEM payload, to keep the UI safe). */
    QVector<StoredKey> listStoredKeys();
    /** Remove a stored key; best-effort. */
    bool removeStoredKey(const QString& id);
    bool storeStoredKeyPassphrase(const QString& id, const QByteArray& passphrase);
    bool retrieveStoredKeyPassphrase(const QString& id, QByteArray& passphraseOut);
    bool removeStoredKeyPassphrase(const QString& id);

    // ---- notes (global notebook, synced via GH sync) -------------------------
    /** Persist the global notes document (HTML; legacy Markdown still readable). */
    bool storeNotesMarkdown(const QString& markdown);
    /** Load notes; returns empty string when absent. */
    QString retrieveNotesMarkdown();

    // ---- diagnostics ---------------------------------------------------------
    /** true if the OS keyring path is active (vs the file-backed fallback). */
    bool usingNativeKeyring() const { return m_usingNative; }

private:
    bool ensureDbKey();
    const QByteArray& dbKey() const { return m_masterKey; }
    bool readDbvault();
    bool persistDbvault();

    QByteArray m_masterKey; // 32-byte dbvault master key (from keyring/fallback)
    QJsonObject m_dbvault;  // decoded secret map from dbvault
    bool m_dbLoaded = false;
    bool m_dbDirty = false;
    bool m_usingNative = false;
};
